# lazygit config
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  # Use our Nerd Font for icons
  nerdFontsVersion: "3"
  # Show file icons in the files panel
  showFileIcons: true
  # Catppuccin Macchiato theme
  theme:
    activeBorderColor:
      - "#8aadf4" # blue
      - bold
    inactiveBorderColor:
      - "#6e738d" # overlay0
    searchingActiveBorderColor:
      - "#eed49f" # yellow
      - bold
    optionsTextColor:
      - "#8aadf4" # blue
    selectedLineBgColor:
      - "#363a4f" # surface0
    cherryPickedCommitFgColor:
      - "#8aadf4" # blue
    cherryPickedCommitBgColor:
      - "#494d64" # surface1
    markedBaseCommitFgColor:
      - "#8aadf4" # blue
    markedBaseCommitBgColor:
      - "#eed49f" # yellow
    unstagedChangesColor:
      - "#ed8796" # red
    defaultFgColor:
      - "#cad3f5" # text
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
disableStartupPopups: true
